language: node_js
node_js:
- '12.13'
install:
- yarn install
- cp README.md projects/ng-sa-data-table/README.md
script:
- yarn lib-build
- cd dist/ng-sa-data-table
cache: yarn
deploy:
  provider: npm
  email: sabeersulaimanpv@gmail.com
  api_key:
    secure: B1beREqyMYFW1gxuO3GGs+J/b4eq1XcL8/rJzW7NRvP9XAJ7VVwKECY50wY3poo0e/5q/7wOk3Gwdt/I4cEMbbW5sila3ads5NxT7YHgaDMSYE6aCla/d3nhY9tj3/qeHgN/ypM+NZgUX1I3Am3rQLyD7uDwW2a2CTExPZuv1mWrFvw/bqWkjadtqY8yt08IO54Svi45lvF/MKHHdEoyDqBgTTArLzZlR8GiI3I65bQbMcdH8jd5XB/jHPjSVj/nYGfVgB/Zgb1fFExuQHtJVAePxGsgtblTcEKdl/QzDxlBwOyD22R9lFSqmYNbqWDY6ywzFW9hzvlqmiPOvwvSyjF6EVy38EL8CvOkJ7mrjLfE0X+8qsS8KT9eN4NE8F1wksS/F7L3ni83zvQ4CQbvDfGVvp1M3vwI6nBX/IxL+X0Z6PN4xuPLKbOc3jypG8Vgf1EMXneVGl/jaSlNoWFJfElIqD5x48F/+tMqC1v++4iiw1jyI8cT70RjMjVM2BAnwOUd76TrAJUX6ZGvDDmDZxKGZC3ygYptY3PqtNNGB+KQYdUa/l1Ivfwy31J551+6Vaa0Aoe7hFkCtBvEQHDQdnrBJbx82fOYVV6zB/3RU3p0zOsP9Q7Z7vkfDjEqzu6MqduLt+zgAfGwFi+3AODSA5KoPN+MmQwNTx0I0fFzsKc=
  on:
    tags: true
  branches:
    only:
      - /^v[0-9]+.*$/
  skip_cleanup: true
