language: node_js
node_js:
  - '12.13'
install:
  - yarn install
script:
  - yarn lib-build
  - cd dist/ng-sa-data-table
cache: yarn
deploy:
  provider: npm
  email: sabeersulaimanpv@gmail.com
  api_key:
    secure: rMeXQWeWfenyIhRaDXVYf5OMqJNjpI+UJYfZnm5uIskLCsO17U7iNHXlFcJt7LjRDJjggx2/2/Ltv0ANF1k4HYtj0K6vATwwV/LbBbKa66mWNNUvKJSXAbypHsY9GPiFvyXLUI3N50ARl0+7tIdEVcdh48g70/lLkTgSMHQqIS63GdtqamLnsOCK1Ke2AB++xH5u6KfIRJ30BQrfdRkAyW41+P+9NXK1CTobHcsFUZYy2DURvc3gkqKjK1py+JaQF6OeBCqrFu0LuZWYkvoAVQxFYDbBLCZDoDdkQlic+kPJuJVZ2k0v/e6nh86LNTJ4R0KOz+OfP11jnIADasOkEEYRZ8DUS8PqA5FQgapo4t8BdcztZKns/JWQNzIRZKEPZyv9b1UMVcATqv3VXjNpuYAL6/EfVEht5hNhjl1rlpGkd9BU2hvd/fCuC2oDVY/p/tuvv4iwQbrCmpQRzruxU23qHki7Ix0y1RMHpZLf+i9EmV+0t/2zacQTYjqo6FXquXLACLoKq+PWucvQdmQiMfH5km+x2gjdC5ImrExYkr50hxwhDOUOhsDn6NI+EtPEpAZZHVFWsFDN5owdSqVUKrMxoIC1NlD9FGmQ2tCqV07B86QYTLnb7z/7dc+XisZu7folOG0MusE99vADxbcF6cIRx//DmcFvPDUO4zzGLtI=
  on:
    branch: master
  skip_cleanup: true